language: java

dist: trusty

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer # http://bit.ly/2qOkihl

before-install:
  - sudo apt-get update -q
  - sudo apt-get install openjfx -y  # For the JavaFX API



script:
  - mvn clean verify
  - mvn clean install
  - mvn test -X
