language: java

dist: trusty

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer # http://bit.ly/2qOkihl

before-install:
  - sudo apt-get update -q
  - sudo apt-get install openjfx -y  # For the JavaFX API

#install: mvn install -V -e

script: mvn clean install
